name: CI

on:
  push:
    branches: ["develop"]
  pull_request: {}
  workflow_dispatch: {}

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust


      - name: Rust Build
        run: cargo build --all-features --all-targets
      - name: Rust Lint - Format
        run: cargo fmt --all --check
      - name: Rust Lint - Clippy
        run: cargo clippy --all-features --all-targets
      - name: Rust Test
        run: cargo test --workspace --all-features
